# # To get started with Dependabot version updates, you'll need to specify which
# # package ecosystems to update and where the package manifests are located.
# # Please see the documentation for all configuration options:
# # https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# version: 2
# updates:
#   - package-ecosystem: "" # See documentation for possible values
#     directory: "/" # Location of package manifests
#     schedule:
#       interval: "weekly"



version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 8
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      # Gabungkan semua minor + patch production
      prod-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      # Gabungkan semua minor + patch development
      dev-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      # Major version tetap terpisah (lebih aman)
      # (tidak digroup)

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
