/* This file is generated by scripts/generate-template-registry.mjs. */
/* Add a self-contained template folder, then run npm run templates:generate. */
import { templateModule as daztoreInv1 } from "./daztore-inv1";
import { templateModule as elegantGold } from "./elegant-gold";
import { templateModule as minimalWhite } from "./minimal-white";

export const generatedTemplateModules = [daztoreInv1, elegantGold, minimalWhite] as const;
