/* This file is generated by scripts/generate-template-registry.mjs. */
/* Add a self-contained template folder, then run npm run templates:generate. */
import { templateModule as elegantGold } from "./elegant-gold";
import { templateModule as minimalWhite } from "./minimal-white";
import { templateModule as weddingDefault } from "./wedding-default";

export const generatedTemplateModules = [elegantGold, minimalWhite, weddingDefault] as const;
